### ISSUE TITLE
[Transferred] Unpaired sequences output when paired only box checked

### ISSUE THREAD

**Issue by mikessh** [antigenomics/vdjdb-web#51]
See https://github.com/antigenomics/vdjdb-db/issues/251 by @dmstandley

**Comment by mikessh** [comment]
@dmstandley its not much of a bug, its related to the following set of conditions
1) You select paired records, paired records are returned by VDJdb-web
2) Next, as ``meta -> Include non-canonical`` and ``meta -> Include unmapped V/J`` checkboxes are unchecked, records that do not have V/J mappings or records with non-canonical CDR3 sequences (not starting with C and ending with F/W) are removed from the search
Perhaps we should make the paired-only filter more smart to act after all filters, what do you think @bvdmitri ?

**Comment by dmstandley** [comment]
I agree it’s not a true bug. Just a result that made me think a bit. For
example, why are alpha J genes missing from so many hla class II entries? I
chatted about this with Fabio and he said it was likely due to poor quality
tetramers for class II.

Anyway, I found that I could match the j genes using the CDR sequence in
most cases. I’m still tweaking the code but I’ll make the results public so
others interested in class II can use them.

Cheers

Daron

**Comment by bvdmitri** [comment]
@mikessh @dmstandley we may add additional checkbox which will force appending all paired records, including ones not matching the filters settings (like export option does).

**Comment by dmstandley** [comment]
Thanks. It might be more intuitive this way.

**Comment by bvdmitri** [comment]
@dmstandley We had implemented this feature in a new release. It is already available via https://vdjdb.cdr3.net/search. New 'Append paired records' checkbox under Gene section was added.
